src/Glossy.Web/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Glossy.Web.Controllers
{
    public class ErrorController : Controller
    {
        //
        // GET: /Error/
        public ActionResult ServerError()
        {
            Response.StatusCode = 500;
            return View();
        }

        public ActionResult NotFound()
        {
            Response.StatusCode = 404;
            return View();
        }
    }
}

src/Glossy.Web/Controllers/GlossaryController.cs
using System.Web.Mvc;
using Glossy.Application.Commands;
using Glossy.Application.Infrastructure;
using Glossy.Application.Models;
using Glossy.Web.ActionFilters;

namespace Glossy.Web.Controllers
{
    [AjaxByConvention]
    public class GlossaryController : Controller
    {
        private readonly ICommandBus _commandBus;
        private readonly IModelBuilder _modelBuilder;

        public GlossaryController(ICommandBus commandBus, IModelBuilder modelBuilder)
        {
            _commandBus = commandBus;
            _modelBuilder = modelBuilder;
        }

        [NoCache] //IE is an aggressive cacher, without this applied it would not fetch
        //the glossary after adding a term.
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Index()
        {
            var model = _modelBuilder.Create<GlossaryModel>();

            return View(model);
        }

        #region Define

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Define()
        {
            var model = new DefineTermModel();

            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Define(DefineTermCommand command)
        {
            if (ModelState.IsValid)
            {
                _commandBus.Execute(command);

                return RedirectToAction("Index");
            }

            var model = new DefineTermModel();

            return View(model);
        }

        #endregion

        #region Re-Define

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Redefine(RedefineTermQuery input)
        {
            RedefineTermModel model = _modelBuilder.Create<RedefineTermQuery, RedefineTermModel>(input);

            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Redefine(RedefineTermCommand command)
        {
            if (ModelState.IsValid)
            {
                _commandBus.Execute(command);

                return RedirectToAction("Index");
            }

            var query = new RedefineTermQuery {Term = command.Term};
            RedefineTermModel model = _modelBuilder.Create<RedefineTermQuery, RedefineTermModel>(query);

            return View(model);
        }

        #endregion

        #region Undefine

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Undefine(UndefineTermQuery input)
        {
            UndefineTermModel model = _modelBuilder.Create<UndefineTermQuery, UndefineTermModel>(input);

            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Undefine(UndefineTermCommand command)
        {
            _commandBus.Execute(command);

            return RedirectToAction("Index");
        }

        #endregion
    }
}

src/Glossy.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Glossy.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Glossy.Web/Views/Glossary/Define.cshtml
@model Glossy.Application.Models.DefineTermModel

@{
    ViewBag.Robots = "index,follow";
    ViewBag.Title = "Define a Term - Glossy";
    ViewBag.Keywords = "Define,Term,Glossary";
    ViewBag.Description = "Define a new term in the glossary of terms";
}

@Html.Partial("_Define", Model)

src/Glossy.Web/Views/Glossary/Index.cshtml
@model Glossy.Application.Models.GlossaryModel

@{
    ViewBag.Robots = "index,follow";
    ViewBag.Title = "Glossary of Terms";
    ViewBag.Keywords = String.Join(",", Model.Entries.Select(entry => entry.Term));
    ViewBag.Description = "The glossary of terms contains a list of important terms and definitions";
}

<div id="list_view" class="glossary-view" data-reload-uri="@Url.Action("Index", "Glossary")">
    @Html.Partial("_Index", Model)
</div>

<div class="form-actions">
    @Html.ActionLink("Define a term", "Define", null, new { @class = "action btn btn-primary" })
</div>

@section ScriptIncludes
{
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/ajax-by-convention.js")" type="text/javascript"></script>
}

src/Glossy.Web/Views/Glossary/Redefine.cshtml
@model Glossy.Application.Models.RedefineTermModel

@{
    ViewBag.Robots = "index,follow";
    ViewBag.Title = "Redefine a Term - Glossy";
    ViewBag.Keywords = "Redefine,Term,Glossary";
    ViewBag.Description = "Redefine an existing term in the glossary of terms";
}

@Html.Partial("_Redefine", Model)

src/Glossy.Web/Views/Glossary/Undefine.cshtml
@model Glossy.Application.Models.UndefineTermModel

@{
    ViewBag.Robots = "index,follow";
    ViewBag.Title = "Undefine a Term - Glossy";
    ViewBag.Keywords = "Undefine,Term,Glossary";
    ViewBag.Description = "Undefine a term from the glossary of terms";
}

@Html.Partial("_Undefine", Model)

src/Glossy.Web/Views/Glossary/_Define.cshtml
@model Glossy.Application.Models.DefineTermModel

@using (Html.BeginForm("Define", "Glossary"))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Define a term</legend>

        <div class="control-group">
            @Html.BSLabelFor(model => model.Command.Term)
            <div class="controls">
                @Html.TextBoxFor(model => model.Command.Term, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(model => model.Command.Term)
            </div>
        </div>

        <div class="control-group">
            @Html.BSLabelFor(model => model.Command.Definition)
            <div class="controls">
                @Html.TextAreaFor(model => model.Command.Definition, new { @class = "input-xlarge", rows = "3" })
                @Html.ValidationMessageFor(model => model.Command.Definition)
            </div>
        </div>

        <div class="form-actions">
            @Html.ActionLink("Back to Glossary", "Index", "Glossary", null, new { @class = "btn btn-cancel" })
            <input class="btn btn-primary" type="submit" value="Define" />
        </div>
    </fieldset>
}

src/Glossy.Web/Views/Glossary/_Index.cshtml
@model Glossy.Application.Models.GlossaryModel

@if (Model.Entries.Count == 0)
{
    <div class="alert alert-info">
        The glossary is currently empty. You can add definitions using the "Define a Term" button below.
    </div>
}
else
{
    <ul class="glossary unstyled">
    @foreach (var entry in Model.Entries)
    {
        <li>
            <div class="actions">
                @Html.ActionLink("Redefine", "Redefine", new { Term = entry.Term }, new { @class = "action btn btn-mini btn-primary" })
                @Html.ActionLink("Undefine", "Undefine", new { Term = entry.Term }, new { @class = "action btn btn-mini btn-danger" })
            </div>
            <h3>@entry.Term</h3>
            <p>@entry.Definition</p>
        </li>
    }
    </ul>
}

src/Glossy.Web/Views/Glossary/_Redefine.cshtml
@model Glossy.Application.Models.RedefineTermModel

@using (Html.BeginForm("Redefine", "Glossary", new { Model.Command.Term }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Redefine a term</legend>
        <div class="control-group">
            @Html.BSLabelFor(model => model.Command.NewTerm)
            <div class="controls">
                @Html.HiddenFor(model => model.Command.Term)
                @Html.TextBoxFor(model => model.Command.NewTerm, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(model => model.Command.NewTerm)
            </div>
        </div>

        <div class="control-group">
            @Html.BSLabelFor(model => model.Command.NewDefinition)
            <div class="controls">
                @Html.TextAreaFor(model => model.Command.NewDefinition, new { @class = "input-xlarge", rows = "3" })
                @Html.ValidationMessageFor(model => model.Command.NewDefinition)
            </div>
        </div>

        <div class="form-actions">
            @Html.ActionLink("Back to Glossary", "Index", "Glossary", null, new { @class = "btn btn-cancel" })
            <input class="btn btn-primary" type="submit" value="Redefine" />
        </div>
    </fieldset>
}

src/Glossy.Web/Views/Glossary/_Undefine.cshtml
@model Glossy.Application.Models.UndefineTermModel

@using (Html.BeginForm("Undefine", "Glossary", new { Model.Command.Term }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Undefine a term</legend>

        <div class="control-group">
            <label class="control-label">Term</label>
            <div class="controls">
                @Html.HiddenFor(model => model.Command.Term)
                <span class="input-xlarge uneditable-input">@Html.DisplayFor(model => model.Command.Term)</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Definition</label>
            <div class="controls">
                <span class="input-xlarge uneditable-input multi-line">@Html.DisplayFor(model => model.Definition)</span>
            </div>
        </div>

        <div class="form-actions">
            @Html.ActionLink("Back to Glossary", "Index", "Glossary", null, new { @class = "btn btn-cancel" })
            <input class="btn btn-danger" type="submit" value="Undefine" />
        </div>
    </fieldset>
}

src/Glossy.Web/Views/Home/Index.cshtml
@{
    ViewBag.Robots = "index,follow";
    ViewBag.Title = "Glossy";
    ViewBag.Keywords = "Glossy,Glossary,Terms,Definitions";
    ViewBag.Description = "Glossy is a web application that allows you to maintain a glossary of terms";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}
<div class="hero-unit">
    
    <div class="thumbnail">
        <div class="image-container">
            <a href="http://www.flickr.com/photos/practicalowl/4098547561/" title="The Worlds Smallest Dictionary by practicalowl, on Flickr"><img src="http://farm3.staticflickr.com/2804/4098547561_3a4c417702_n.jpg" width="320" height="235" alt="The Worlds Smallest Dictionary"></a>
        </div>
    </div>

    <h1>Welcome to Glossy</h1>
    <p>Glossy is a web application that allows you to maintain a glossary of terms</p>
    <p>You can:</p>

    <ul class="unstyled features">
        <li><i class="icon-check"></i> View a list of terms sorted alphabetically</li>
        <li><i class="icon-check"></i> Define a new term</li>
        <li><i class="icon-check"></i> Redefine an existing term</li>
        <li><i class="icon-check"></i> Undefine an obsolete term</li>
    </ul>

    <p>
        @Html.ActionLink("View the Glossary", "Index", "Glossary", null, new { @class = "btn btn-primary btn-large" })
    </p>
</div>

src/Glossy.Web/Views/Shared/ApplicationError.cshtml
@{
    ViewBag.Title = "Application Error - Glossy";
}

<div class="alert alert-error">
    <h2>500 - Application Error</h2>
    Something has gone horribly wrong! The error has been logged and we will endevour to invesitigate
    <p>the problem as soon as possible. You can try again but if the problem persists please come back later.</p>
    <p>@Html.ActionLink("Back to Glossary", "Index", "Glossary", null, new { @class = "btn btn-danger" })</p>
</div>

src/Glossy.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found - Glossy";
}

<div class="alert">
    <h2>404 - Not Found</h2>
    <p>Sorry but we couldn't find what you are looking for.</p>
    <p>@Html.ActionLink("Back to Glossary", "Index", "Glossary", null, new { @class = "btn btn-warning" })</p>
</div>

src/Glossy.Web/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    @Html.Partial("_Meta")
    <!--[if lte IE 8]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/bootstrap-overrides.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css"/>
    @RenderSection("HeaderIncludes", false)
</head>

<body>
    <div class="container">
        @RenderBody()

        @RenderSection("ScriptIncludes", false)
    </div>
</body>
</html>

src/Glossy.Web/Views/Shared/_Layout.cshtml
@{ Layout = "~/Views/Shared/_BaseLayout.cshtml"; }

<div class="row">
    <div class="span8 offset2">
        <header>
            <a class="thumbnail" href="http://www.flickr.com/photos/practicalowl/4098547561/" title="The Worlds Smallest Dictionary by practicalowl, on Flickr"><img src="http://farm3.staticflickr.com/2804/4098547561_3a4c417702_s.jpg" width="75" height="75" alt="The Worlds Smallest Dictionary" /></a>
            <h1>Glossy</h1>
        </header>

        <div class="content">
            @RenderBody()
        </div>
    </div>
</div>

@section HeaderIncludes
{
    @RenderSection("HeaderIncludes", false)
}
@section ScriptIncludes
{
    @RenderSection("ScriptIncludes", false)
}

src/Glossy.Web/Views/Shared/_Meta.cshtml
@if(ViewBag.Robots != null)
{
    <meta name="robots" content="@ViewBag.Robots" />
}
@if(ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}